/**
 * Centralized text constants for UI strings.
 * Add new entries here to keep text consistent and enable easy localisation.
 */
export const TEXT = {
  PLAY_NOW: "Play Now",
  PLAY_MUSIC: "Play Music",
  PAUSE_MUSIC: "Pause Music",
  SELECT_GAMES: "Select Games",
  SELECT_GAME: "Select Game",
  PICK_SCRAP_PAPER: "Pick a scrap paper to start doodling!",
  CHOOSE_ADVENTURE: "Choose your adventure",
  ACTIVE_GAMES: "Active Games",
  UPCOMING_LOCKED_GAMES: "Upcoming & Locked Games",
  START_MATCH: "Start Match",
  LOCKED: "Locked",
  COMING_SOON: "Coming Soon",
  PENCIL_RECORD: "PENCIL RECORD",
  WIN_STREAK: "Win Streak",
  GAMES_PLAYED: "Games Played",
  DEFAULT_SHEET: "Sheet #3",
  PENCIL_BATTLE_01: "Pencil Battle No. 01",
  DOODLE_XO: "DOODLE XO",
  GRAPH_PAPER_SHOWDOWN: "the graph paper showdown",
  SHARPENING_PENCILS: "Sharpening pencils...",
  READY_TO_DOODLE: "Ready to doodle!",
  STUDY_HALL_SECRET: "Study Hall Secret:",
  STUDY_HALL_TIP:
    "Tip: Corners give you the edge! Take three corners to build an unstoppable double fork.",
  DESK_MATE_MATCH: "Desk Mate Match #14",
  FIVE_WINS: "5 wins",
  CLASS_IN_SESSION: "Class in session • Keep scribbles quiet",
  ROOM_4B: "Room 4B",
  DOODLER_18: "Doodler #18",
  DEFAULT_STARS: "★ 1,240",
  HOT: "HOT!",
  TWO_PLAYERS: "2 PLAYERS",
  XO_TITLE: "XO Tic-Tac-Toe",
  XO_SUBTITLE: "Classic pen & paper showdown",
  DOTS_BOXES_TITLE: "Dots & Boxes",
  DOTS_BOXES_SUBTITLE: "Connect line grid",
  HANGMAN_TITLE: "Hangman",
  HANGMAN_SUBTITLE: "Guess secret word",
  SOON_BADGE: "SOON",
  LVL_5_BADGE: "LVL 5",
  COPYRIGHT: `© ${new Date().getFullYear()} XOMastermind`,
};
